cc_binary(
    name = "avl",
    srcs = ["avl.cpp", "avl.hpp"]
)

cc_binary(
    name = "heap",
    srcs = ["heap.cpp", "heap.hpp"]
)

cc_binary(
    name = "trie",
    srcs = ["trie.cpp", "trie.hpp"]
)

cc_binary(
    name = "hashtable",
    srcs = ["hashtable.cpp", "hashtable.hpp", "hash.hpp"]
)

cc_binary(
    name = "bloom_filter",
    srcs = ["bloom_filter.cpp", "bloom_filter.hpp", "packed_vector.hpp", "hash.hpp"]
)

cc_binary(
    name = "mergesort",
    srcs = ["mergesort.cpp", "mergesort.hpp"]
)

cc_binary(
    name = "quicksort",
    srcs = ["quicksort.cpp", "quicksort.hpp"]
)

cc_binary(
    name = "strtok",
    srcs = ["strtok.cpp", "strtok.hpp"]
)

cc_binary(
    name = "anagrams",
    srcs = ["anagrams.cpp", "hashtable.hpp", "quicksort.hpp", "hash.hpp"]
)
