cc_test(
    name = "avl",
    srcs = [
        "avl.cpp",
        "avl.hpp",
    ],
)

cc_test(
    name = "heap",
    srcs = [
        "heap.cpp",
        "heap.hpp",
    ],
)

cc_test(
    name = "trie",
    srcs = [
        "trie.cpp",
        "trie.hpp",
    ],
)

cc_test(
    name = "hashtable",
    srcs = [
        "hash.hpp",
        "hashtable.cpp",
        "hashtable.hpp",
    ],
)

cc_test(
    name = "bloom_filter",
    srcs = [
        "bloom_filter.cpp",
        "bloom_filter.hpp",
        "hash.hpp",
        "packed_vector.hpp",
    ],
)

cc_test(
    name = "mergesort",
    srcs = [
        "mergesort.cpp",
        "mergesort.hpp",
    ],
)

cc_test(
    name = "quicksort",
    srcs = [
        "quicksort.cpp",
        "quicksort.hpp",
    ],
)

cc_test(
    name = "strtok",
    srcs = [
        "strtok.cpp",
        "strtok.hpp",
    ],
)

cc_test(
    name = "anagrams",
    srcs = [
        "anagrams.cpp",
        "hash.hpp",
        "hashtable.hpp",
        "quicksort.hpp",
    ],
)

cc_test(
    name = "compiler",
    srcs = ["compiler.cpp"],
)
